import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar, Footer } from "@/components";
import toast, {Toaster} from 'react-hot-toast'
import CartContextProvider from "@/contexts/cartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pixel",
  description: "Generated by create next app",
    icons: {
    icon: "/logo.png",       // ✅ favicon in tab
    shortcut: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <CartContextProvider>
          <Navbar />
          {children}
          <Toaster/>
          <Footer />
        </CartContextProvider>
      </body>
    </html>
  );
}
